### ISSUE TITLE
При удалении плагина – удалять за собой

### ISSUE THREAD

**Issue by mihdan** [mihdan/mihdan-mailru-pulse-feed#12]
Привет.

1. При удалении плагина – “деактивировать” -> “удалить” – не происходит удаление опции из wp_options “wptrt_notice_dismissed_mihdan-mailru-pulse-feed” – я так понимаю эта опция была из-за вордпресс нотиса что я закрыл: “Поставьте 5 звёзд плагину”.

2. Ставить эту опцию без флага “autoload” true. Она нужна не везде – а только в админке (еще лучше чтоб только на странице настроек плагина, а не по всей админке мозолила глаз). А так получается что мы ее тянем и в фронтенде.

К таким вещам надо быть внимательней.

3. Вот скриншот https://yadi.sk/i/geHU5KmwruEU6A – это последние опции в БД. Я так понимаю они тоже от плагина остались после его удаления?
Смотри – сервис смок теста https://plugintests.com/plugins/mihdan-mailru-pulse-feed/latest долистай до секции “Options wp_options” (4)
– я так понимаю и эти 4-ре опции плагин добавляет? им бы ваш префикс добавить – чтоб было понятно что это от вас и снова к autoload – пересмотрите использование с флагом true – не нужен там autoload в настройки. Стоит получать их по необходимости. А то все это на фронтенд части где это не нужно получается.

Спасибо.

https://wordpress.org/support/?p=12412715

**Comment by mihdan** [comment]
Владимир, следить, можно тут в репе @Otshelnik-Fm

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-mailru-pulse-feed/commit/62c8f6bb690a4e7f9821dab0fc6930af5a9ee362

https://github.com/mihdan/mihdan-mailru-pulse-feed/commit/5a805ced56745f2005ca56f4b5d5db1cfc183323

**Comment by Otshelnik-Fm** [comment]
А я туда по старой ссылке от кажется Александра (прошлый тикет на мой доп) пришел. Гит, так гит))

**Comment by mihdan** [comment]
Поддержка на wp.org, код, идеи, ошибки, предложения - можно тут.
