### ISSUE TITLE
OpenWebAnalytics и ОШИБКА 500: Internal Server Error.

### ISSUE THREAD

**Issue by r4hx** [mihdan/mihdan-mailru-pulse-feed#18]
При использование плагина OpenWebAnalytics формирование фида падает с ошибкой. 

`
➜  tmp wget https://site.ru/feed/mihdan-mailru-pulse-feed/
--2020-10-26 10:14:59--  https://site.ru/feed/mihdan-mailru-pulse-feed/
Распознаётся site.ru (site.ru)… 11.11.11.11
Подключение к site.ru (site.ru)|11.11.11.11|:443... соединение установлено.
HTTP-запрос отправлен. Ожидание ответа… 500 Internal Server Error
2020-10-26 10:15:02 ОШИБКА 500: Internal Server Error.
`

Текст ошибки в error_log

`
site.ru [Mon Oct 26 10:18:32 2020] [warn] [pid 503] sapi_apache2.c(349): [client 2.2.2.2:34294] PHP Warning:  DOMDocument::loadHTML(): Empty string supplied as input in /home/c/dsa/site.ru/public_html/wp-content/plugins/mihdan-mailru-pulse-feed/vendor/imangazaliev/didom/src/DiDom/Document.php on line 293
site.ru [Mon Oct 26 10:18:32 2020] [error] [pid 503] sapi_apache2.c(349): [client 2.2.2.2:34294] PHP Fatal error:  Uncaught RuntimeException: Cannot convert empty document to Element in /home/c/dsa/site.ru/public_html/wp-content/plugins/mihdan-mailru-pulse-feed/vendor/imangazaliev/didom/src/DiDom/Document.php:681\nStack trace:\n#0 /home/c/dsa/site.ru/public_html/wp-content/plugins/mihdan-mailru-pulse-feed/includes/class-main.php(532): DiDom\\Document->toElement()\n#1 /home/c/dsa/site.ru/public_html/wp-includes/class-wp-hook.php(287): Mihdan\\MailRuPulseFeed\\Main->wrap_image_with_figure('', 100)\n#2 /home/c/dsa/site.ru/public_html/wp-includes/plugin.php(206): WP_Hook->apply_filters('', Array)\n#3 /home/c/dsa/site.ru/public_html/wp-content/plugins/mihdan-mailru-pulse-feed/templates/feed.php(32): apply_filters('mihdan_mailru_p...', '', 100)\n#4 /home/c/dsa/site.ru/public_html/wp-content/plugins/mihdan-mailru-pulse-feed/includes/class-main.php(794): require('/home/c/cp87161...')\n#5 /home/c/dsa/site.ru/public_html/wp-includes/class-wp-hook.php(287): Mihdan\\MailRuPul in /home/c/dsa/site.ru/public_html/wp-content/plugins/mihdan-mailru-pulse-feed/vendor/imangazaliev/didom/src/DiDom/Document.php on line 681
`

Проблему решил отключением плагина, если есть ценность в исправление этой ошибки - хорошо, если нет - переживу работу сайта без плагина openwebanalytics :)

**Comment by mihdan** [comment]
https://github.com/mihdan/mihdan-mailru-pulse-feed/commit/762822efdf6e22853ab84e8355760669f0a43f8a
